language: node_js
node_js:
- '7'
script:
- echo "Deploy!!"
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --token=${FIREBASE_TOKEN}
deploy:
  provider: firebase
  token:
    secure: cJ0PbkPzYqTyAb36zQvmuaS6DweOR1wyLJRlu8IgbpXBxdHJJBTa3EVrTSx5NouwyWn8BWeHtZvzsXLjshryVP+8afbBmGhCR3BcAqBpM8u+6XNjzb8B+as4MYlcPuEu2+FHrJEBnpa7B4l6cuU8Iz5DRekTHVzFfBim6ves2018bIKSqA57WLuYmlD/A4OxTQfE0gOag3YrUv5DGlWQUcbbM3dFe4u0dqTdo+w8gVPBYi3LcGlJV2j9OsFag+AdOASr+UWB+5cRAwxn4REOdQM1H5kX4JOvauK4MnzRHDlhXwGNwrydCExz0NCJZpZivjzCQDiQweXwKzPgYBK3qqp4cDCc4YQD3DhX6DKu6ltgBK32F1P9FV6W/IAOadUuARmKFa4DbL+bz5dZH/Jg75awq2HCZHEPu8cUOatVkN7WnFIlTzMvtXNn4elOb2GhwTF8dg4gXoJExZjNFhgFuDeeqn1YQyclGVZIICKmdUdpIrFo003pVuRg2q7cJp15PeCmQy/J91WrxTqWH7zqRoC71szTVv2ZtVcC4Ny7z1nvKikjpWUNQA4VHPaqIYSS+LaFTirmCA666Ksyp3VqNsiE0GHKYiTK7fPpSbpOt2RporvT1iPwTQD0s/gg5I9YnJS99EDIdH+PHXzpLyf/BPcR6CB/yeut73ml6VTKPdI=
