language: node_js
node_js:
- '7'
script:
- echo "Deploy!!"
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --project astrology-9999 --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  token:
    secure: M+6efTKGh7lGWPUfWagUg7qJ9k+nb2+xi/wv1LF/U+DXPu6YuSntdX4t+9o9L0PMcXXOEYKhfjEe9otdktB5OJ+aCH2FpkJCq8ceERaTXBKxb0KC8hHZHcOPLaq+zmn3zfgo3QGaWe+upq2mNEyJE/cyRmuhu1kyL0wGFopPt6AVePht2MRrNV4Tk02NSSM3jMbmnIzpcnouV4ipE7E6Jsc7jhL2qajgEhN5R1K5no5rA9hB+2uYjsD3bD05OFdAQzsFb7t/N/bRdAum6nvjuJTM9xgRfhxMW8FATkymudy2/avrXREjnAOwSKEgeSJeqYbql7cBZYC4deH2r9XZaf9Zh/zDYuJUF/jvAzfIDyp9bndGF6LkWjAX5eVOVtkpcNWQx/g68ghQi5pz+eFF1iwVY8KF454TC1OZq+ErnDeWJTEH+4sLirLBtJOoURuuet9KImOgDFzDjQTIsQp/kgX5iCsJT8dT0M388HtghPz3dTNj9uEsr9+FEpgU8X7KOlCVAb96ENRb03Mx0JWBjygWUYgW2FJuKQ8+MNs6bkoPxdJlQB9PQz31sG6EZ2szp9t7sp69pFcQjSBddXHVFCxlTe7yL7qzqlzAgbE3jHaUJZe4cBPWK9I0ZaFUjgZWYh6ggnxqoWXV8IlFWtgbUOPF4UGhyKZjlshmgKZXRkI=

