language: node_js
node_js:
- '7'
script:
- echo "Deploy!!"
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --project astrology-9999 --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  token:
    secure: q/QUH0HWOO3WEGhfpsUqzumamUxuzaoP7p1QQBybmKM+VpH6LUjjgkltv8PRQb7h65eEZf1lE4WJc5thmUi3rePW0O9hVPPVx0fGcOnt4PbZ6xnFvDbbf19gLlkZWcoYoGWQFvzquQ3LldkEI/d3F+ZZZkZDTdvqyuTM6tcunkTBTbxd3iKlGFdqBmjOlJVFEVfVUQ6p562yQ+KUpSvhlUmse7ns/niobJU+wvbS4zUE7xoRNDV15GrhovwzAhs9J7AYTHh+7d1Sodbw0zrTcaBLDChf4UNO5z6NpUtSbGAyCQ+PfVvLqnX0Lf+E06TPDtcQZlUrKNYfnkVQ/zPm3LLhIxFhD3CNf3w9rivVbq3a/Ba14qnpHcBTl2O232vkb7jgSees4Olix2rGOZp4USNkPIJZpVkxRvxwFyqzzdNyAVrMV4HCMcIfBiAJKOqSJHgJLvjHD00J7w+zPPEqI1sGtEbgmD91QjejN/EbY7y6mvf73rYTKqL7bQ8tcMY173NxItf5s/N9ZklOaUWCxhDbqLDoUhtfIc2Pt9Yz1OgsgdGjcMD/+AlfL5lYW8+hQN6nyhWf+WozED+GoX7w97Wgp2TCZUNj3zqhHSsCNdsgUXA7EqXKxSBRk5taT+4ZiRG+uPLYWpsIHdgtHhWpqqDZv9YBICAr7FFrUb+sxqE=