language: node_js
node_js:
- '7'
script:
- echo "Deploy!!"
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --project astrology-9999 --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  token:
    secure: zFLc0Nc6jcG7pIj17oAfXaWlTVJEfJcb2DMkZYNVL9SK/NM9ct5FGF6J2IPd9BTab54jB3k69BQROhZtm6XT7Y/tbCesATxfTb28n92oZe/2WvSvSH9ady/HQysFvbxTm5+xEHZB29wvJhuUPrYirubDzayizW9IhaW8d1rfV9Pvf674DrZduoVz6CO8qbd87H8DquehXh/V5puUTuVK8jBzRQxj8eP1g6T9AQTrXEl97RzLh+gx41+Jx4qPWlmlZAy2hGwghuw14eGrnXVQMiDM8J9AOhGVNSYlB8u5DPSHnvH7OLyqVZGG73aquql2rDEwFsYVGVdG51UBUx/SKdHWEUOVKhq7uaZips9py6cIUufGcfuca+Cvp+E3MN7QSY/lRq/1GqBuRmn6oBmzLnqUepXn8yprfXkocu/hpXrxDzs5ttdkql80OT4AoF7UIkFRDEerISGRvApy7WPCZnnXeDpGL6iQyAramlWC+KBz2DRVXaYHMdIGrwnQPGC/743NE5qBErCW49OPPqyEyWo5u8tQyrfInzdyo7UVIAL/DqkJHqqBZENwNr/0mNi74fyur0qjyZnhJ75hJ7w09xVQUb8BeWvh284/RH7VExoTYu43YrdueAM81YQsVvz3HhudAHqafF5Gnvt+XdLSCPLb6t/avauiI2RUe5B1WxI=